---
title: "Lab 1"
author: "Jessica Kosie"
date: "January 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data
```{r}
library(rio)
tweets <- import("data/rstats_tweets.rds")
```

##Commit 2
```{r commit2}
#install.packages("ggplot2")
head(tweets)
library(utf8)
library(dplyr)
library(forcats)
library(ggplot2)
countscreen <- count(tweets, vars = screen_name)
countscreen <- arrange(countscreen, desc(n))
countscreen25 <- dplyr::slice(countscreen, 1:25)

(graph1 <- ggplot(countscreen25, aes(x = fct_reorder(vars, n, desc = FALSE), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("screen_name"))
```

## Commit 3
```{r pretty_graph, fig.height=10 , fig.width=10}
(pretty_graph <- ggplot(countscreen25, aes(x = fct_reorder(vars, n, desc = FALSE), y = n)) +
  geom_bar(stat = "identity", fill="cornflowerblue", alpha = 0.6) +
  coord_flip() +
  xlab("Twitter Screen Name")+
  ylab("Count")+
 theme_minimal(base_size=15)+
  ggtitle("Most prolific #rstats tweeters")+
  labs(subtitle = "Top 25 screen names displayed"))
```


## Commit 4
```{r}
library(tidyverse)

# Create variable for tweets rounded by month and year
tweets_month <- tweets %>% 
  mutate(month = lubridate::round_date(created_at, unit = "month")) %>% 
  filter(month < lubridate::as_datetime("2019-01-01 UTC"))

# Count tweets by month and year
month_count <- tweets_month %>% 
  count(month)

# Plot
ggplot(month_count, aes(x = month, y = n)) +
  geom_smooth(method = "loess", se = T) +
  geom_line()
```

## Commit 5
```{r, fig.width = 10, fig.height = 10}
# Pretty plot
ggplot(month_count, aes(x = month, y = n)) +
  geom_smooth(color = "magenta", method = "loess", se = FALSE, size = 1.5) +
  geom_line(color = "gray40", size = 1.5) +
  theme_minimal(base_size = 18) +
  geom_area(alpha = .3, fill = "cornflowerblue") +
  ggtitle("Growth of the #rstats hashtag on twitter over time") +
  labs(x = "Year (data summarized by month)", y ="Number of #rstats tweets")
```